# -*- coding: utf-8 -*-

{
    'name': 'EBizCharge Payment Acquirer',
    'category': 'Accounting/Payment',
    'summary': 'Payment Provider: EBizCharge Implementation',
    'version': '1.2',
    'description': """EBizCharge Payment Gateway""",
    'depends': ['base','contacts', 'web', 'mail', 'payment', 'sale', 'account', 'stock','helpdesk_inherit'],
    'data': [
        'security/ir_security.xml',
        'security/ir.model.access.csv',

        'views/payment_ebizcharge_menuitems.xml',
        'views/payment_request_bulk_email.xml',
        'views/email_receipt_view.xml',
        'views/email_template_view.xml',
        'views/transaction_history_view.xml',

        'views/payment_token_view.xml',
        'views/payment_transaction_view.xml',
        'data/payment_acquirer_data.xml',
        'views/res_config_setting_view.xml',

        'views/res_company_view.xml',
        'views/sale_register_payment_view.xml',
        'views/sale_order_view.xml',
        'views/account_move_view.xml',
        'views/account_register_payment_view.xml',
        'views/account_payment_view.xml',
        'views/product_template_view.xml',
        'views/res_partner_view.xml',
        'views/payment_method_ui_view.xml',
        'views/batch_processing_views.xml',
        'views/upload_customers.xml',
        'views/upload_saleorders.xml',
        'views/upload_products.xml',
        'views/upload_invoice_view.xml',
        'views/upload_credit_notes.xml',
        'views/contact_us.xml',
        'views/invoice_payment_link_bulk_views.xml',
        'views/so_payment_link_bulk_views.xml',
        'views/download_payment_views.xml',
        'views/emv_device_transaction.xml',
        'wizard/wizard_process_transaction_views.xml',
        'wizard/wizard_avs_validation_view.xml',
        'wizard/wizard_email_invoice_view.xml',
        'wizard/wizard_email_receipt_view.xml',
        'wizard/wizard_emv_device_view.xml',
        'wizard/message_wizard.xml',
        'wizard/wizard_void_transaction_view.xml',
        'wizard/wizard_request_payment_method_view.xml',
        'schedular/schedule.xml',
        'wizard/wizard_add_new_card_view.xml',
        'wizard/wizard_add_card_validation_view.xml',
        'wizard/wizard_show_pending_ebiz_email_view.xml',
        'wizard/wizard_add_new_ach_view.xml',
        'wizard/wizard_multi_sync_resp_view.xml',
        'wizard/wizard_request_email_payment_bulk_view.xml',
        'wizard/wizard_card_expiring_soon_view.xml',
        'wizard/wizard_payment_link_view.xml',
        'wizard/wizard_generate_so_payment_link_view.xml',
        'wizard/wizard_sale_order_avs_validation.xml',
        'wizard/transaction_detail_wizard.xml',
        'wizard/download_payment_confirm_view.xml',
        'wizard/wizard_generate_payment_link_view.xml',
        'reports/inherited_account_invoice_report_view.xml',
        'views/ebizcharge_instance_config_view.xml',
    ],
    'qweb': [
        "static/src/xml/menu.xml",
        "static/src/xml/field_masking.xml",
        'static/src/xml/help_widget.xml',
    ],
    'images': [
        'static/description/banner.png',
    ],
    'price': 0,
    'currency': 'USD',
    'installable': True,
    'external_dependencies': {'python': ['zeep']},
    'assets': {
        'web.assets_frontend': [
            'payment_ebizcharge_crm/static/src/scss/portal_payment.scss',
        ],
        'web.assets_backend': [
            'payment_ebizcharge_crm/static/src/scss/backend.scss',
            'payment_ebizcharge_crm/static/src/components/**/*',
        ],
    },
    'license': 'LGPL-3',

}
